version: '3.7'

# demo of the image

services:

  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        PHP_IMAGE: 24hoursmedia/pfpm74trift:latest
    volumes:
      - ./local/fs:/var/www/html
    dns:
      - 1.1.1.1